/**
 * @file main-css.mutator.js
 * @description Mutator for main.css file to inject theme and branding
 * @date 2026-03-22
 * @author Totistack Team
 */

import fs from 'fs-extra';
import path from 'path';
import { logger } from '../utils/logger.js';
import { InstallError } from '../errors/index.js';

/**
 * Update main.css with theme variables and imports
 * @param {string} projectRoot - Project root
 * @param {object} branding - Branding configuration
 * @returns {Promise<void>}
 */
export async function mutateMainCss(projectRoot, branding) {
  const cssPath = path.join(projectRoot, 'src', 'assets', 'css', 'main.css');
  
  if (!await fs.pathExists(cssPath)) {
    throw new InstallError('main.css not found');
  }

  try {
    let content = await fs.readFile(cssPath, 'utf8');
    
    // Inject CSS variables from branding
    const cssVariables = generateCssVariables(branding);
    
    // Add theme variables at the top
    content = `/* Theme Variables - Generated by Totistack */\n${cssVariables}\n\n${content}`;
    
    // Add Tailwind directives if not present
    if (!content.includes('@tailwind base')) {
      content = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n${content}`;
    }
    
    await fs.writeFile(cssPath, content);
    logger.info('Updated main.css with theme variables');
  } catch (err) {
    throw new InstallError(`Failed to update main.css: ${err.message}`, { cause: err });
  }
}

/**
 * Generate CSS variables from branding config
 * @param {object} branding - Branding configuration
 * @returns {string}
 */
function generateCssVariables(branding) {
  const variables = [];
  
  // Colors
  if (branding.colors) {
    Object.entries(branding.colors).forEach(([key, value]) => {
      variables.push(`  --color-${key}: ${value};`);
    });
  }
  
  // Fonts
  if (branding.fonts) {
    Object.entries(branding.fonts).forEach(([key, value]) => {
      variables.push(`  --font-${key}: ${value};`);
    });
  }
  
  // Spacing
  if (branding.spacing) {
    Object.entries(branding.spacing).forEach(([key, value]) => {
      variables.push(`  --spacing-${key}: ${value};`);
    });
  }
  
  // Border radius
  if (branding.borderRadius) {
    Object.entries(branding.borderRadius).forEach(([key, value]) => {
      variables.push(`  --radius-${key}: ${value};`);
    });
  }
  
  // Animations
  if (branding.animations) {
    Object.entries(branding.animations).forEach(([key, value]) => {
      variables.push(`  --animation-${key}: ${value};`);
    });
  }
  
  return `:root {\n${variables.join('\n')}\n}`;
}